sudo: required
dist: trusty

language:
    cpp

compiler:
    - clang # 3.5.0
    - gcc # 4.8.4

install:
    # Install dependencies
    - sudo apt-get update -qq
    - sudo apt-get install -qy cmake libqt4-dev libqt4-opengl-dev libgdal1-dev libcgal-dev libfreenect-dev libvxl1-dev 
    # libdxflib-dev
    # CC submodules
    - git submodule init && git submodule update 

before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release 
      -DINSTALL_QHPR_PLUGIN=ON 
      -DINSTALL_QPCV_PLUGIN=ON 
      -DINSTALL_QPOISSON_RECON_PLUGIN=ON 
      -DINSTALL_QEDL_PLUGIN=ON 
      -DINSTALL_QSRA_PLUGIN=ON 
      -DINSTALL_QSSAO_PLUGIN=ON 
      -DINSTALL_QPCV_PLUGIN=ON 
      -DOPTION_USE_GDAL=ON 
      -DINSTALL_QKINECT_PLUGIN=ON 
      -DLIBFREENECT_INCLUDE_DIR="/usr/include" 
      -DLIBFREENECT_LIBRARY_FILE="/usr/lib/x86_64-linux-gnu/libfreenect.so" 
      -DINSTALL_QFACETS_PLUGIN=ON 
      -DOPTION_USE_SHAPE_LIB=ON 
      -DINSTALL_QGMMREG_PLUGIN=ON 
      -DINSTALL_QANIMATION_PLUGIN=ON ..
      
      # For now :
      # - qRansacSD fail on Clang
      # - no libav/FFMPEG. Version in repos is < 10.7 (no frame.h)
      # - could not use CGAL from Ubuntu (< 4.3)
      # - DXFLIB need a better cmake to handle libdxflib from Ub
script:
    # We use only 4 core because gcc and clang can be memory hungry
    - make -j4
