Document: cloudcompare
Title: Debian cloudcompare Manual
Author: <insert document author here>
Abstract: This manual describes what cloudcompare is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cloudcompare/cloudcompare.sgml.gz

Format: postscript
Files: /usr/share/doc/cloudcompare/cloudcompare.ps.gz

Format: text
Files: /usr/share/doc/cloudcompare/cloudcompare.text.gz

Format: HTML
Index: /usr/share/doc/cloudcompare/html/index.html
Files: /usr/share/doc/cloudcompare/html/*.html
